require File.join(File.dirname(__FILE__), "test_generator_helper.rb")
require 'fileutils'

class TestTboxGenerator < Test::Unit::TestCase
  include RubiGen::GeneratorTestHelper

  def setup
    bare_setup
  end

  def teardown
    bare_teardown
  end

  # Some generator-related assertions:
  #   assert_generated_file(name, &block) # block passed the file contents
  #   assert_directory_exists(name)
  #   assert_generated_class(name, &block)
  #   assert_generated_module(name, &block)
  #   assert_generated_test_for(name, &block)
  # The assert_generated_(class|module|test_for) &block is passed the body of the class/module within the file
  #   assert_has_method(body, *methods) # check that the body has a list of methods (methods with parentheses not supported yet)
  #
  # Other helper methods are:
  #   app_root_files - put this in teardown to show files generated by the test method (e.g. p app_root_files)
  #   bare_setup - place this in setup method to create the APP_ROOT folder for each test
  #   bare_teardown - place this in teardown method to destroy the TMP_ROOT or APP_ROOT folder after each test

  def test_generator_without_options
    run_generator('tbox', [APP_ROOT], sources)
    
    assert_generated_file   "rakefile.rb"
    assert_generated_file   "README"
    assert_generated_file   "MIT-LICENSE"
    assert_directory_exists "lib/samples"
    assert_generated_file   "lib/samples/right_triangle.rb"
    assert_generated_file   "lib/tbox.rb"
    assert_directory_exists "test/samples"
    assert_generated_file   "test/samples/test_right_triangle.rb"
    assert_directory_exists "test/data"
    assert_generated_file   "test/data/file.txt"
    assert_generated_file   "test/test_io.rb"
    assert_generated_file   "test/test_helper.rb"
    
    FileUtils::cd(APP_ROOT) do
      puts "Running generated rakefile in #{FileUtils::pwd}"
      `rake`
      raise "Error occured while running generated rakefile" if ($?.to_s != "0")
    end
    
    p app_root_files
  end

  private
  def sources
    [RubiGen::PathSource.new(:test, File.join(File.dirname(__FILE__),"..", generator_path))
    ]
  end

  def generator_path
    "app_generators"
  end
end
