#!/usr/bin/env ruby

begin
  require 'shubox'
rescue LoadError
  require 'rubygems'
  require 'shubox'
end

require 'test_unit_cleaner/lib/test_unit_cleaner'

puts Shubox::TestUnitCleaner.new.run(ARGV)
