#!/usr/bin/env ruby

begin
  require 'shubox'
rescue LoadError
  require 'rubygems'
  require 'shubox'
end

require 'test_unit_cleaner/lib/test_unit_cleaner'

doc = ARGF.readlines 
puts Shubox::TestUnitCleaner.new.clean_class(doc)